### ISSUE TITLE
Issue with login when deployed to AWS Lambda using SST

### ISSUE THREAD

**Issue by NicholasG04** [payloadcms/next-payload-demo#10] opened 2023-09-09 19:49 UTC
Hi, we've been trying to deploy this application to AWS Lambda using SST, and this has been mostly successful. However, whilst most API routes seem to return the correct data (e.g. /api/users/me and /api/users/init), the create-first-user and login routes don't seem to return any data. They always return 200 with no payload.

This leads to the behaviour that creating the first user silently works (it adds it to the database) but then nothing happens on the front-end. Similarly, logging in seems to authenticate (checking the lambda logs, it does show failures correctly) but nothing happens on the front-end. The button just goes back to being clickable, and 200 no content is returned by the POST /api/users/login.

**Comment by ruchernchong** [comment] 2023-10-21 21:02
Same problem here but I was not able to add the first user to the database!

**Comment by jacobsfletch** [comment] 2024-04-12 14:52
Hey there @NicholasG04 and @ruchernchong, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed as completed by jacobsfletch** 2024-04-12 14:52 UTC

**Comment by ruchernchong** [comment] 2024-04-12 14:53
> Hey there @NicholasG04 and @ruchernchong, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

Hey @jacobsfletch, I saw the launch of Payload 3.0 and its direct integration with Next.js. It is really awesome and I cannot wait to try it. I also totally understand that this issue should no longer be a problem after launch of 3.0!
