### ISSUE TITLE
S3 uploads aren't appearing in bucket

### ISSUE THREAD

**Issue by modulareverything** [payloadcms/next-payload-demo#15] opened 2024-03-21 16:51 UTC
Hey,

I've not used Amazon S3 before so I'm just trying to get to grips with it. I've deployed this repo to a Vercel account and can access it, log in, etc.

However, when I upload something to the Media section, the file appears to upload but the actual image is missing. I can also see when refreshing my S3 bucket that no files are being uploaded.

![Screenshot 2024-03-21 at 4 45 24 pm](https://github.com/payloadcms/next-payload-demo/assets/8567692/da0b86c7-fc95-4888-9d61-bbc197f58a12)

It's creating the file structure correctly if I view the source:
https://s3.eu-west-2.amazonaws.com/my-s3-bucket/9029b33821838ae5857867291cc051b2-1.jpg

So I think I have something misconfigured, but I'm not sure what and testing this is a bit of a pain as I have to keep redeploying to test anything out.

My .env file looks like this (I've faked out the data but it's more or less the same):

```env
MONGODB_URI=mongodb+srv://xxxxxx:yyyyyy@db-mongodb-lon1-54217-4c10acd1.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-lon1-54217
PAYLOAD_SECRET=MY_PAYLOAD_SECRET
PAYLOAD_CONFIG_PATH=dist/payload.config.js
NEXT_PUBLIC_APP_URL=http://localhost:3000
PAYLOAD_PUBLIC_CMS_URL=http://localhost:3000
S3_ACCESS_KEY_ID=XXXXYYYYZZZZZ
S3_SECRET_ACCESS_KEY=fAKeAc+Ce55k3y
S3_REGION="Europe (London) eu-west-2"
NEXT_PUBLIC_S3_ENDPOINT="https://s3.eu-west-2.amazonaws.com"
NEXT_PUBLIC_S3_BUCKET="my-s3-bucket"
PAYLOAD_PRIVATE_REGENERATION_SECRET=MY_PAYLOAD_SECRET
NEXT_PRIVATE_REGENERATION_SECRET=MY_PAYLOAD_SECRET
ANALYZE=false
```

My S3 access key ID and secret I set up in the security credentials section on AWS (https://us-east-1.console.aws.amazon.com/iam/home#/security_credentials)

I can see here that the "Access key last used" is still "none"

Am I missing something here?

**Comment by jacobsfletch** [comment] 2024-04-12 14:51
Hey @modulareverything, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed as completed by jacobsfletch** 2024-04-12 14:51 UTC
