### ISSUE TITLE
Usage of vercel cache

### ISSUE THREAD

**Issue by tilman** [payloadcms/next-payload-demo#5] opened 2023-05-31 05:15 UTC
Are the payload client calls using fetch under the hood so that they are cached especially for dynamic sites?
https://github.com/payloadcms/next-payload-demo/blob/722af1c13ffa8bcd1b648cc6b9e7b299b7bbd875/app/(site)/%5Bslug%5D/page.tsx#L11

As far as I understood it they payload client methods are directly using the mongodb api without fetch in-between correct?

What would be the best implementation to implement the vercel/next.js fetch? https://nextjs.org/docs/app/building-your-application/data-fetching/caching#react-cache
Seems like getPayload is imported from `payload` package directly and I guess you don't want to have next.js specifiy code in this package. So maybe it would be nice to add a `getPayload` payload function to [next-payload package](https://github.com/payloadcms/next-payload) which is using getPayload from payload package but wraps every cacheable function (like find/findMany) in a cache function?

**Comment by jmikrut** [comment] 2023-06-26 17:50
To me this points to a huge complexity in the way that NextJS just simply extends `fetch` with its own caching in the first place. 

This is a very good question. I guess the answer here depends on where and how you want to cache database calls. Caching is a massive topic, and there are lots of ways to go about it depending on the platform that you leverage.

For example, if you're just running Payload on an Express server normally, you might not want to cache Payload API responses directly. But, other times, you might definitely want to cache and in turn logically cache-bust as documents are updated. In Payload Cloud, we are building a way to do this on Cloudflare that will run totally behind the scenes (cache GET responses, and cache-bust when updates happen).

> As far as I understood it they payload client methods are directly using the mongodb api without fetch in-between correct?

This is correct. The Payload client talks directly to the database, no fetch involved.  

> So maybe it would be nice to add a getPayload payload function to [next-payload package](https://github.com/payloadcms/next-payload) which is using getPayload from payload package but wraps every cacheable function (like find/findMany) in a cache function?

This depends largely on what you want to see happen and would only be useful in a subset of applications. For example, in this demo package, the `[slug]/page.tsx` that you referenced above statically renders its content, so no caching to Payload is really necessary.  

If you wanted to dynamically render certain pages, to me, that would imply that you would _**not**_ want to render pages statically in the first place, so you should not be caching anything at all anyway.

But, if you did want to dynamically render pages with some dynamic content but other content from Payload cached, then that's where I think the `react-cache` approach would come in. And that would be application-specific.

Does that make sense?

**Comment by jacobsfletch** [comment] 2024-04-12 14:53
Hey @tilman, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed as completed by jacobsfletch** 2024-04-12 14:53 UTC
