### ISSUE TITLE
Using routes in app directory

### ISSUE THREAD

**Issue by feledori** [payloadcms/next-payload-demo#11] opened 2023-09-14 12:11 UTC
Is there a reason to why this template still uses the pages directory for the api endpoints? Just curious. :)

**Comment by jacobsfletch** [comment] 2024-04-12 14:51
Hey @feledori, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed as completed by jacobsfletch** 2024-04-12 14:51 UTC
