### ISSUE TITLE
[BUG] All layouts disappear from view when adding new layouts to existing page

### ISSUE THREAD

**Issue by Snailedlt** [payloadcms/next-payload-demo#9] opened 2023-09-06 11:09 UTC
## What?

Sometimes when editing a page's layouts the layouts seemingly disappear (see video below).

https://cdn.discordapp.com/attachments/1148881416684326952/1149252601561501717/dashboard_-_Grnn_Vekst_-_Google_Chrome_2023-09-05_13-53-11.mp4

## Why?
It turns out that for some reason the mongodb database changes the layout type from an array of objects to an object of objects. This seems to be the reason for all the errors:
![image](https://github.com/payloadcms/next-payload-demo/assets/43886029/ccd28c47-376a-46f7-87ca-b35568bd6375)

"testing three" works fine since it's an array of objects
![image](https://github.com/payloadcms/next-payload-demo/assets/43886029/fa5246c5-666d-4df1-8f9d-f0730981121f)

"testing four" has been edited after its initial creation, and therefore does not show the layouts, which in the db is an object of objects.
![image](https://github.com/payloadcms/next-payload-demo/assets/43886029/808fed7b-f71a-4165-a189-c8f27438005d)

After adding another layout to "testing three" the db objects look like this:
![image](https://github.com/payloadcms/next-payload-demo/assets/43886029/f3ad1eef-f75e-4f8c-9241-70c06931d73b)

## Steps to reproduce

1. Download the `next-payload-demo` repo: https://github.com/payloadcms/next-payload-demo/tree/61597476e18cd920001fcca95b7fd7b45b374480
2. run
```sh
yarn install
pnpm import
```
3. delete `yarn.lock`
4. add the following dependencies to `package.lock`
```
    "snappy": "^7.2.2",
    "aws-crt": "^1.18.0",
    "aws4": "^1.12.0",
    "bson-ext": "^4.0.3",
    "kerberos": "^2.0.1",
    "lucide-react": "^0.268.0",
    "mongodb": "^5.7.0",
    "mongodb-client-encryption": "^2.9.0",
    "mongoose": "^7.4.3"
```
5. run
```sh
pnpm install
pnpm dev
```
6. follow the steps in the video at the top of this thread to add a new page with a content layout, edit the page and add more layouts/blocks.

7. After having done all of this you can safely hard reset to the main branch's latest commit and the issue should still occur: `git reset --hard 61597476e18cd920001fcca95b7fd7b45b374480`

## More info

- Deleting the `.next` folder seemingly has no effect
- This console message shows up when creating or updating a page `[10:19:05] INFO (payload): Error hitting regeneration route for '/testing-six'`. `testing-six` here is the slug of the edited page.
- This happens both for `yarn` and `pnpm`

Full debugging thread on discord: https://discord.com/channels/967097582721572934/1148881416684326952

**Comment by JarrodMFlesch** [comment] 2023-09-06 16:39
@Snailedlt can we pin down exactly what causes this? I am unable to repro when using the demo and yarn. I did not run it with pnpm or the deps you listed. I would first like you to attempt to pin down what is causing it, is it actually the packages? is it pnpm? Try recreating it with just yarn, no packages, then yarn with packages. If that works still, try just pnpm no packages, and then lastly pnpm with packages. Also it would be great if you could try this with one package at a time to see if one is the culprit.

Let me know what you come up with, thanks!

p.s. the video is 0 seconds long 😄

**Comment by Snailedlt** [comment] 2023-09-06 16:48
Thanks for responding so quickly!
The issue isn't related to the packages as far as I can see. In the reproduction step 7 I deleted all pnpm stuff and reset it to the main branch. So it's neither an issue with pnpm nor with the extra packages. At first I was suspecting the .next cache, but deleting that didn't have any effect either.

Maybe it's some sort of corruption with the mongodb database? I'm not really sure, but I suspect the reason you weren't able to reproduce it is related to either the .env file or the mongodb database. Afaik those are the only two differences between my local environment and the main brnach in this repo. That is unless there's some gitignored file I'm missing.


I'm not near my PC atm, but I'll send you my .env file later today or at latest tomorrow.

Edit: I apparantly sent the wrong video too... Will edit that later too :)

**Comment by Snailedlt** [comment] 2023-09-07 12:34
@JarrodMFlesch I updated the issue to include the correct video.

I'm able to consistently reproduce the bug by following the instructions in the issue description.

In order to reproduce the bug I believe you have to migrate to pnpm. After migrating the bug is there regardless of if you switch back to yarn or not, which is why I've come to the conclusion the bug has to be caused by either a caching issue, a corruption in the database, or changes in a gitignored file.

If you're still unable to reproduce, try using the same pnpm, yarn and node versions I'm using:
```sh
> pnpm --version
8.6.12
> node --version
v19.9.0
> yarn --version
1.22.11
```

As for system details, I'm using a Windows 11 machine. Node is installed via [nvm-windows](https://github.com/coreybutler/nvm-windows), yarn is installed via npm and pnpm is installed via [winget](https://pnpm.io/installation#using-winget)

**Comment by jacobsfletch** [comment] 2024-04-12 14:53
Hey @Snailedlt, this repo as well as [next-payload](https://github.com/payloadcms/next-payload) will soon be archived because they've been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed as completed by jacobsfletch** 2024-04-12 14:53 UTC
